name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: macOS-15
            swift: '6.3'
          - os: ubuntu-24.04
            swift: '6.3'
          - os: windows-latest
            swift: '6.3'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: SwiftyLab/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}

    - name: Install ZeroMQ dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libzmq3-dev libsodium-dev

    - name: Install ZeroMQ dependencies
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
        "VCPKG_DEFAULT_TRIPLET=x64-windows-static-md" >> $env:GITHUB_ENV

        & "$env:VCPKG_INSTALLATION_ROOT\vcpkg.exe" install zeromq:x64-windows-static-md

    - name: Checkout
      uses: actions/checkout@v7

    - name: Build
      run: swift build

    - name: Test
      run: swift test
